### ISSUE TITLE
Downgrade?

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/INTO-CPS-Association.github.io#9]
Hugo downgraded 20-sim 4C in https://github.com/INTO-CPS-Association/INTO-CPS-Association.github.io/commit/7d9110943befc3939a22c735bef419f111862faf.

However, with the new release it has been upgraded again.

Can you guys resolve why this downgrade occurred and what the challenges are? 

Feel free to close this issue any of you, if it is no longer relevant.

**Comment by margro** [comment]
I've no idea why it was downgraded. The 2.2 prerelease version is the correct version (with source code FMU import and Raspberry Pi support).

**Comment by CThuleHansen** [comment]
@idhugo can you clarify this? Otherwise we will keep the 2.2 prerelease version.

**Comment by idhugoid** [comment]
Yes. We were applying the INTO-CPS training course at our own course at AU, yet AU had a license for version 2.1... The downgrade motivation was to keep version consistency during the course edition. I think there is no problem in reverting the upgrade...

**Comment by CThuleHansen** [comment]
Thank you. Cheers
